### ISSUE TITLE
Build doesn't work in the typescript version

### ISSUE THREAD

**Issue by umstek** [frontarm/create-react-blog#2]
**Problem:**  
The line:  
https://github.com/frontarm/create-react-blog/blob/8c0631c48c083768335eb4ccce9cc2d60467a7e9/template-ts/package.json#L28
tries to run a shell/cmd with `node-ts` instead of the actual `navi-scripts.js` itself.  

**Solution:**
Replacing the line with `"build": "react-scripts build && ts-node -O {\\\"module\\\":\\\"commonjs\\\"} node_modules/navi-scripts/bin/navi-scripts.js build",` fixes the problem.

**Comment by jamesknelson** [comment]
Could you let me know what platform you're using? This works fine for me on Mac OS 10.14, but perhaps the `.bin` directory is mac specific?

**Comment by umstek** [comment]
I'm using Windows. Didn't try on Linux yet.

**Comment by jamesknelson** [comment]
I see, things seem to work differently on mac and windows. Thanks for submitting the fix! I've just merged it in.
