### ISSUE TITLE
build error with public URL

### ISSUE THREAD

**Issue by wulucxy** [frontarm/create-react-blog#8]
@jamesknelson great work！

I have a question：if  I set `PUBLIC_URL=/xxx/yyy/` in `.env` config，`npm run build` will throw an error：

```javascript
.......
The project was built assuming it is hosted at /qingtong/papaya-blog/.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  http://bit.ly/CRA-deploy

navi-scripts: Using config at /work/FE/gatsby/react-blog/navi.config.js
Error: Could not load script: "/qingtong/papaya-blog/static/js/30.7a7c1dba.chunk.js"
    at onErrorWrapped (/work/FE/gatsby/react-blog/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:38:19)
    at Object.check (/work/FE/gatsby/react-blog/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:72:23)
``` 

actually，`react-scripts build` is ok，it seems `navi-scripts` have some problem with `PUBLIC_URL`。

I can not find any document related to this in the project。

**Comment by jamesknelson** [comment]
This looks to be an issue in navi-scripts instead of this project, closing this for now.

**Comment by karolis-adapt** [comment]
Found this issue through github search. Couldn't find anything related to `PUBLIC_URL` in the navi repo (where `navi-scripts` is kept). @jamesknelson any updates on this? Can't find any documentation either
