### ISSUE TITLE
need a baseUrl config

### ISSUE THREAD

**Issue by wulucxy** [frontarm/create-react-blog#9]
@jamesknelson I have a problem with this project。

I have a public server，which I can only have the access to specific path。

for example：

the host is：`www.xxx.yyy`，my page need to be visited by `www.xxx.yyy/qingtong/blog/`。I pushed
my `build` to the server。page will show just server render，when client begin to render，I only get the `404` page。

I think there need to be a `baseUrl` config，in my example，`baseUrl` is equal to `/qingtong/blog/`，so SSR and CSR will be equal to each other。

thanks for your work。

**Comment by henryqrm** [comment]
@wulucxy, I opened PR with fix. #10
